"""empty message

Revision ID: 0fc4c3d53cb0
Revises: 2e4175a7462b
Create Date: 2026-04-08 17:38:45.437470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fc4c3d53cb0'
down_revision = '2e4175a7462b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_all_access', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rol', schema=None) as batch_op:
        batch_op.drop_column('has_all_access')

    # ### end Alembic commands ###
