"""empty message

Revision ID: 142d8f902735
Revises: 46ec1ecb4975
Create Date: 2026-02-25 15:14:01.679406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '142d8f902735'
down_revision = '46ec1ecb4975'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_catalog',
    sa.Column('id_ac', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id_competence'], ),
    sa.PrimaryKeyConstraint('id_ac')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_catalog')
    # ### end Alembic commands ###
