"""empty message

Revision ID: 2638a7ef2724
Revises: da3753b4314e
Create Date: 2026-02-21 13:26:58.890426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2638a7ef2724'
down_revision = 'da3753b4314e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('indicator_dependencies',
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['depends_on_id'], ['indicator.id_indicator'], ),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id_indicator'], ),
    sa.PrimaryKeyConstraint('indicator_id', 'depends_on_id')
    )
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_date_end', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('planned_target', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('evidence_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('actual_observations', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('context_denominator', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('context_denominator')
        batch_op.drop_column('actual_observations')
        batch_op.drop_column('evidence_url')
        batch_op.drop_column('planned_target')
        batch_op.drop_column('planned_date_end')

    op.drop_table('indicator_dependencies')
    # ### end Alembic commands ###
