"""empty message

Revision ID: 2e4175a7462b
Revises: 09633a90b6ed
Create Date: 2026-03-24 18:48:36.653812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4175a7462b'
down_revision = '09633a90b6ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_change_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_change_log', schema=None) as batch_op:
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
