"""empty message

Revision ID: 3fc946852c74
Revises: 52ae5e9d00da
Create Date: 2026-02-07 20:25:59.490593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc946852c74'
down_revision = '52ae5e9d00da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_means', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('observations', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicator', schema=None) as batch_op:
        batch_op.drop_column('observations')
        batch_op.drop_column('verification_means')

    # ### end Alembic commands ###
