"""empty message

Revision ID: 4202fa383801
Revises: 
Create Date: 2026-01-17 15:25:40.530921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4202fa383801'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('project_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('main_goal_target', sa.Integer(), nullable=False),
    sa.Column('main_goal_description', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_project'),
    sa.UniqueConstraint('project_code')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('name_rol', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('name_rol')
    )
    op.create_table('indicator',
    sa.Column('id_indicator', sa.Integer(), nullable=False),
    sa.Column('ind_code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id_project'], ),
    sa.PrimaryKeyConstraint('id_indicator'),
    sa.UniqueConstraint('ind_code')
    )
    op.create_table('location',
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('place_type', sa.String(length=50), nullable=False),
    sa.Column('place_name', sa.String(length=150), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id_project'], ),
    sa.PrimaryKeyConstraint('id_location')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('profile', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('activity',
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('implementation_date', sa.DateTime(), nullable=False),
    sa.Column('achievement_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id_indicator'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id_location'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id_project'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_activity')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity')
    op.drop_table('user')
    op.drop_table('location')
    op.drop_table('indicator')
    op.drop_table('rol')
    op.drop_table('project')
    # ### end Alembic commands ###
