"""empty message

Revision ID: 52ae5e9d00da
Revises: 54feb77a9f4c
Create Date: 2026-02-06 22:48:24.801592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ae5e9d00da'
down_revision = '54feb77a9f4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_theory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('project_competence_id', sa.Integer(), nullable=False),
    sa.Column('theory_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_competence_id'], ['project_competence.id_pc'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id_project'], ),
    sa.ForeignKeyConstraint(['theory_template_id'], ['theory_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_theory_id', sa.Integer(), nullable=False),
    sa.Column('result_template_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_theory_id'], ['project_theory.id'], ),
    sa.ForeignKeyConstraint(['result_template_id'], ['result_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicator', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_result_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'project_result', ['project_result_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('indicator', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('project_result_id')

    op.drop_table('project_result')
    op.drop_table('project_theory')
    # ### end Alembic commands ###
