"""empty message

Revision ID: 6a9631fa4645
Revises: 45072961a99b
Create Date: 2026-01-30 14:59:27.150839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a9631fa4645'
down_revision = '45072961a99b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('province',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('municipality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('province_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipality.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('province_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('municipality_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('parish_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'parish', ['parish_id'], ['id'])
        batch_op.create_foreign_key(None, 'municipality', ['municipality_id'], ['id'])
        batch_op.create_foreign_key(None, 'province', ['province_id'], ['id'])
        batch_op.drop_column('municipality')
        batch_op.drop_column('province')
        batch_op.drop_column('parish')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parish', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('province', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('municipality', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parish_id')
        batch_op.drop_column('municipality_id')
        batch_op.drop_column('province_id')

    op.drop_table('parish')
    op.drop_table('municipality')
    op.drop_table('province')
    # ### end Alembic commands ###
