"""empty message

Revision ID: 8fd15dd2af88
Revises: df8c05a35e68
Create Date: 2026-03-03 18:13:56.292116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd15dd2af88'
down_revision = 'df8c05a35e68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_public_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement_record', schema=None) as batch_op:
        batch_op.drop_column('evidence_public_id')

    # ### end Alembic commands ###
