"""empty message

Revision ID: be165a643eec
Revises: 3fc946852c74
Create Date: 2026-02-10 21:42:32.500901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be165a643eec'
down_revision = '3fc946852c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_verification_mean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('indicator_verification_means',
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('mean_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id_indicator'], ),
    sa.ForeignKeyConstraint(['mean_id'], ['master_verification_mean.id'], ),
    sa.PrimaryKeyConstraint('indicator_id', 'mean_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator_verification_means')
    op.drop_table('master_verification_mean')
    # ### end Alembic commands ###
