"""empty message

Revision ID: c40da5e44cef
Revises: 
Create Date: 2026-01-28 15:55:05.357299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c40da5e44cef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competence',
    sa.Column('id_competence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id_competence'),
    sa.UniqueConstraint('name')
    )
    op.create_table('project',
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('donor_name', sa.String(length=100), nullable=True),
    sa.Column('project_name', sa.String(length=200), nullable=True),
    sa.Column('main_objective', sa.Text(), nullable=True),
    sa.Column('results_summary', sa.Text(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_project'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rol',
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('name_rol', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id_rol'),
    sa.UniqueConstraint('name_rol')
    )
    op.create_table('location',
    sa.Column('id_location', sa.Integer(), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=False),
    sa.Column('municipality', sa.String(length=100), nullable=False),
    sa.Column('parish', sa.String(length=100), nullable=True),
    sa.Column('community_institution', sa.String(length=100), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id_project'], ),
    sa.PrimaryKeyConstraint('id_location')
    )
    op.create_table('theory_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id_competence'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('profile', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.id_rol'], ),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('email')
    )
    op.create_table('project_competence',
    sa.Column('id_pc', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id_competence'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['user.id_user'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id_project'], ),
    sa.PrimaryKeyConstraint('id_pc')
    )
    op.create_table('result_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('output', 'outcome', name='result_types'), nullable=False),
    sa.Column('theory_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['theory_id'], ['theory_template.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_competence',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('competence_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['competence_id'], ['competence.id_competence'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('user_id', 'competence_id')
    )
    op.create_table('indicator_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['result_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('indicator',
    sa.Column('id_indicator', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_total', sa.Float(), nullable=False),
    sa.Column('target_men', sa.Float(), nullable=False),
    sa.Column('target_women', sa.Float(), nullable=False),
    sa.Column('target_disability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id_project'], ),
    sa.ForeignKeyConstraint(['template_id'], ['indicator_template.id'], ),
    sa.PrimaryKeyConstraint('id_indicator')
    )
    op.create_table('activity',
    sa.Column('id_activity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('implementation_date', sa.DateTime(), nullable=False),
    sa.Column('achievement_men', sa.Float(), nullable=False),
    sa.Column('achievement_women', sa.Float(), nullable=False),
    sa.Column('achievement_disability', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id_indicator'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id_location'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ),
    sa.PrimaryKeyConstraint('id_activity')
    )
    op.create_table('indicator_location_goal',
    sa.Column('id_ilg', sa.Integer(), nullable=False),
    sa.Column('indicator_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('total_target', sa.Float(), nullable=False),
    sa.Column('men', sa.Float(), nullable=False),
    sa.Column('women', sa.Float(), nullable=False),
    sa.Column('disability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicator.id_indicator'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id_location'], ),
    sa.PrimaryKeyConstraint('id_ilg')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('indicator_location_goal')
    op.drop_table('activity')
    op.drop_table('indicator')
    op.drop_table('indicator_template')
    op.drop_table('user_competence')
    op.drop_table('result_template')
    op.drop_table('project_competence')
    op.drop_table('user')
    op.drop_table('theory_template')
    op.drop_table('location')
    op.drop_table('rol')
    op.drop_table('project')
    op.drop_table('competence')
    # ### end Alembic commands ###
