"""empty message

Revision ID: f1bfa3988688
Revises: f97719d3868b
Create Date: 2026-03-18 21:47:24.535485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bfa3988688'
down_revision = 'f97719d3868b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monitoring_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievement_record', schema=None) as batch_op:
        batch_op.drop_column('monitoring_comment')

    # ### end Alembic commands ###
