"""empty message

Revision ID: f35ba3a6f894
Revises: 6a9631fa4645
Create Date: 2026-01-30 15:25:33.766139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35ba3a6f894'
down_revision = '6a9631fa4645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('municipality_province_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'province', ['province_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('parish', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('parish_municipality_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'municipality', ['municipality_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parish', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('parish_municipality_id_fkey'), 'municipality', ['municipality_id'], ['id'])

    with op.batch_alter_table('municipality', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('municipality_province_id_fkey'), 'province', ['province_id'], ['id'])

    # ### end Alembic commands ###
